################################################################################
# \file platform.mk
# \version 1.1
#
# \brief
# Platform-dependent variables
#
################################################################################
# \copyright
# (c) 2018-2026, Infineon Technologies AG, or an affiliate of Infineon
# Technologies AG.  SPDX-License-Identifier: Apache-2.0
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
################################################################################

CORE_SUFFIX = m33

#redefine DEVICE_MODE from bsp.mk
#DEVICE_MODE=SECURE

# Set to 1 to enable SE Runtime Services implementation of crypto,
# otherwise PSA mbedtls implementation used
USE_IFX_SE_RT ?= 0

# MCUBoot library search path for this platform (set by 'make getlibs')
PLATFORM_MCUBOOT_SEARCH = $(SEARCH_ifx-mcuboot-psc3p8)

PLATFORM_DEFINES += CM33_STACK_LIMIT=0x200
PLATFORM_INCLUDES = 
PLATFORM_SOURCES = 

PLATFORM_CHUNK_SIZE = 4096U
PLATFORM_MEMORY_ALIGN = 512U
PLATFORM_MAX_TRAILER_PAGE_SIZE = 512U

PLATFORM_ALIGNMENT = 1
PLATFORM_ERASE_VALUE = 0
PLATFORM_MIN_ERASE_SIZE = 0x200
###############################################################################
# Application dependent definitions
# MCUBootApp
###############################################################################

ifeq ($(APPNAME), bootloader)
    FLASH_OFS = 0

    # ARM toolchain: the scatter file uses CBUS addresses (0x12000000) for I-cache
    # performance. Convert hex file addresses from CBUS to SBUS (0x32000000) so
    # JLink can program the device. CBUS and SBUS differ by 0x20000000 and alias
    # the same physical flash.
    ifeq ($(TOOLCHAIN), ARM)
        PLATFORM_POSTBUILD += \
            mv -f $(BINARY_OUT_PATH)/$(APPNAME).hex $(BINARY_OUT_PATH)/$(APPNAME)_cbus.hex;\
            $(CY_ELF_TO_HEX_TOOL) -I ihex -O ihex --change-addresses 0x20000000 $(BINARY_OUT_PATH)/$(APPNAME)_cbus.hex $(BINARY_OUT_PATH)/$(APPNAME).hex;
    endif

    ifeq ($(BOOT_MODE), signed)
        FLASH_OFS := $(BOOT_HEADER_SIZE)

        PLATFORM_DEFINES += MCUBOOT_ENCRYPT_PREBUILT_KEY=1
        PLATFORM_DEFINES += MCUBOOT_ENCRYPT_PREBUILT_KEY_LEN=138
        PLATFORM_DEFINES += MCUBOOT_ENCRYPT_PREBUILT_KEY_ADDR=0x03407644

        SIGN_ARGS = sign-image \
            -H $(BOOT_HEADER_SIZE) \
            --align $(PLATFORM_ALIGNMENT) \
            --image-version '1.0.0' \
            -S $(BOOTLOADER_SIZE) \
            -R $(PLATFORM_ERASE_VALUE) \
            --public-key-format full \
            --pubkey-encoding raw \
            --signature-encoding raw \
            --key $(OEM_KEY_FILE) \
            --min-erase-size $(PLATFORM_MIN_ERASE_SIZE) \
            --hex-addr $(BOOTLOADER_ORIGIN) \
            --overwrite-only
        
        ifneq ($(BOOT_RECORD_VALUE), )
            SIGN_ARGS += --boot-record $(BOOT_RECORD_VALUE)
        endif

        PLATFORM_POSTBUILD += mv -f $(BINARY_OUT_PATH)/$(APPNAME).hex $(BINARY_OUT_PATH)/$(APPNAME)_raw.hex;\
            $(CY_ELF_TO_HEX_TOOL) $(CY_ELF_TO_HEX_OPTIONS) $(BINARY_OUT_PATH)/$(APPNAME)_raw.hex $(BINARY_OUT_PATH)/$(APPNAME)_unsigned.hex;\
            $(CY_TOOL_edgeprotecttools_EXE_ABS) $(SIGN_ARGS) -i ./$(BINARY_OUT_PATH)/$(APPNAME)_unsigned.hex -o ./$(BINARY_OUT_PATH)/$(APPNAME).hex;
    endif

    PLATFORM_LINKER_SCRIPT = linker/TOOLCHAIN_$(TOOLCHAIN)/linker

    FEATURE_CONFIG ?= $(PLATFORM_PATH)/feature_config.json
    # PLATFORM_PREBUILD += $(CY_PYTHON_PATH) $(MCUBOOT_CY_PATH)/scripts/feature.py run -f $(FEATURE_CONFIG) -p $(MCUBOOT_CY_PATH)/platforms/memory/PSC3/flashmap/platform_properties.json -n $(AUTOGENERATED_DIR)/feature_config.mk
    PLATFORM_PREBUILD += $(CY_PYTHON_PATH) $(MCUBOOT_CY_PATH)/scripts/feature.py run -f $(FEATURE_CONFIG) -p $(MCUBOOT_CY_PATH)/platforms/memory/$(FAMILY)/flashmap/platform_properties.json -n $(AUTOGENERATED_DIR)/feature_config.mk.tmp

    # Two-pass build for sign_key.c generation
    # Only generate when image validation is enabled (either boot or upgrade validation)
    # Check validation status: enabled if NOT skipping boot validation OR NOT skipping upgrade validation
    IMAGE_VALIDATION_ENABLED := 0
    ifneq ($(MCUBOOT_SKIP_BOOT_VALIDATION), 1)
        IMAGE_VALIDATION_ENABLED := 1
    endif
    ifneq ($(MCUBOOT_SKIP_UPGRADE_VALIDATION), 1)
        IMAGE_VALIDATION_ENABLED := 1
    endif

    # Only set up sign_key.c generation rules when NOT running clean targets
    ifeq ($(filter clean clean_proj clean_proj_autogenerated,$(MAKECMDGOALS)),)
        ifeq ($(IMAGE_VALIDATION_ENABLED), 1)
            # Handle LMS key generation (via restart pattern, similar to ECDSA)
            ifneq ($(LMS_PUBLIC_KEY), )
                # Generate lms_sign_key.c only when it doesn't exist (deleted by app.mk when config changes)
                # No prerequisites - relies on file deletion to trigger regeneration
                $(AUTOGENERATED_DIR)/lms_sign_key.c:
					@$(EDGE_PROTECT_TOOLS) convert-key --fmt C_ARRAY -k $(LMS_PUBLIC_KEY) -o $(AUTOGENERATED_DIR)/lms_sign_key.c --var-name lms_pub_key
                # The sentinel depends on lms_sign_key.c - when lms_sign_key.c is generated, recreate sentinel
                $(AUTOGENERATED_DIR)/.lms_sign_key.mk: $(AUTOGENERATED_DIR)/lms_sign_key.c
					@touch $@

                # Include sentinel - if missing, Make will run lms_sign_key.c target, then restart
                -include $(AUTOGENERATED_DIR)/.lms_sign_key.mk
            endif

            ifneq ($(XMSS_PUBLIC_KEY), )
                # Generate xmss_sign_key.c only when it doesn't exist (deleted by app.mk when config changes)
                # No prerequisites - relies on file deletion to trigger regeneration
                $(AUTOGENERATED_DIR)/xmss_sign_key.c:
					@$(EDGE_PROTECT_TOOLS) convert-key --fmt C_ARRAY -k $(XMSS_PUBLIC_KEY) -o $(AUTOGENERATED_DIR)/xmss_sign_key.c --var-name xmss_pub_key

                # The sentinel depends on xmss_sign_key.c - when xmss_sign_key.c is generated, recreate sentinel
                $(AUTOGENERATED_DIR)/.xmss_sign_key.mk: $(AUTOGENERATED_DIR)/xmss_sign_key.c
					@touch $@

                # Include sentinel - if missing, Make will run xmss_sign_key.c target, then restart
                -include $(AUTOGENERATED_DIR)/.xmss_sign_key.mk
            endif

            ifneq ($(MLDSA_PUBLIC_KEY), )
                # Generate ml_dsa_sign_key.c only when it doesn't exist (deleted by app.mk when config changes)
                # No prerequisites - relies on file deletion to trigger regeneration
                $(AUTOGENERATED_DIR)/ml_dsa_sign_key.c:
					@$(EDGE_PROTECT_TOOLS) convert-key --fmt C_ARRAY -k $(MLDSA_PUBLIC_KEY) -o $(AUTOGENERATED_DIR)/ml_dsa_sign_key.c --var-name mldsa_pub_key

                # The sentinel depends on ml_dsa_sign_key.c - when ml_dsa_sign_key.c is generated, recreate sentinel
                $(AUTOGENERATED_DIR)/.ml_dsa_sign_key.mk: $(AUTOGENERATED_DIR)/ml_dsa_sign_key.c
					@touch $@

                # Include sentinel - if missing, Make will run ml_dsa_sign_key.c target, then restart
                -include $(AUTOGENERATED_DIR)/.ml_dsa_sign_key.mk
            endif
            
            # Handle ECDSA key generation (via restart pattern)
            ifneq ($(ECDSA_PUBLIC_KEY), )
                ifneq ($(USE_SFLASH_KEYS), 1)
                    # Generate sign_key.c only when it doesn't exist (deleted by app.mk when config changes)
                    # No prerequisites - relies on file deletion to trigger regeneration
                    $(AUTOGENERATED_DIR)/ecdsa_sign_key.c:
						@$(EDGE_PROTECT_TOOLS) convert-key --fmt C_ARRAY -k $(ECDSA_PUBLIC_KEY) -o $(AUTOGENERATED_DIR)/ecdsa_sign_key.c --var-name ecdsa_pub_key

                    # The sentinel depends on ecdsa_sign_key.c - when ecdsa_sign_key.c is generated, recreate sentinel
                    $(AUTOGENERATED_DIR)/.ecdsa_sign_key.mk: $(AUTOGENERATED_DIR)/ecdsa_sign_key.c
						@touch $@

                    # Include sentinel - if missing, Make will run ecdsa_sign_key.c target, then restart
                    -include $(AUTOGENERATED_DIR)/.ecdsa_sign_key.mk
                endif
            endif

            # Handle EC256 encryption key generation (via restart pattern)
            ifeq ($(ENC_IMG), 1)
                ifneq ($(USE_ENCRYPTION_KDF_CTR), 1)
                    ifneq ($(ENC_PRIVATE_KEY), )
                        # Generate enc_key.c only when it doesn't exist (deleted by app.mk when config changes)
                        # No prerequisites - relies on file deletion to trigger regeneration
                        $(AUTOGENERATED_DIR)/ec256_enc_key.c:
							@$(EDGE_PROTECT_TOOLS) convert-key --fmt C_ARRAY -k $(ENC_PRIVATE_KEY) -o $(AUTOGENERATED_DIR)/ec256_enc_key.c --var-name ec256_enc_priv_key

                        # The sentinel depends on ec256_enc_key.c - when ec256_enc_key.c is generated, recreate sentinel
                        $(AUTOGENERATED_DIR)/.ec256_enc_key.mk: $(AUTOGENERATED_DIR)/ec256_enc_key.c
							@touch $@

                        # Include sentinel - if missing, Make will run ec256_enc_key.c target, then restart
                        -include $(AUTOGENERATED_DIR)/.ec256_enc_key.mk
                    endif
                endif
            endif
        endif
    endif

    PLATFORM_INCLUDES += ../platforms/PSC3_P8/mcuboot_config
    # Hardware rollback counter support
    ifeq ($(USE_HW_ROLLBACK_PROT), 1)
        PLATFORM_SOURCES += $(wildcard $(MCUBOOT_CY_PATH)/platforms/security_counter/PSC3_P8/*.c)
        PLATFORM_INCLUDES += $(MCUBOOT_CY_PATH)/platforms/security_counter/PSC3_P8
        PLATFORM_DEFINES += CY_RBC_ROLLBACK_COUNTERS_NUM=$(MCUBOOT_IMAGE_NUMBER)
        PLATFORM_DEFINES += CY_RBC_CHECKSUM_LENGTH=32
        PLATFORM_DEFINES += CY_RBC_ALIGN=$(PLATFORM_MEMORY_ALIGN)
    endif

    ifeq ($(USE_PROT_CONTEXT_SWITCH), 1)
        PLATFORM_DEFINES += USE_PROT_CONTEXT_SWITCH
    endif

    # Cryptolite hardware acceleration for ECDSA signature verification
    ifneq ($(ECDSA_PUBLIC_KEY), )
        PLATFORM_DEFINES += USE_CRYPTOLITE_ECDSA
    endif

    ifeq ($(ENC_IMG), 1)
        ifeq ($(USE_ENCRYPTION_KDF_CTR), 1)
            # Enable CS-PSC3X8 KDF-CTR for PSC3_P8 platform when encryption is enabled
            DEFINES += USE_ENCRYPTION_KDF_CTR=1
            DEFINES += USE_FUNC_ID

            # Add CS-PSC3X8 crypto library for KDF-CTR support            
            INCLUDES += $(MCUBOOT_CY_PATH)/platforms/crypto/PSC3_P8

            # Hardware implementation needs crypto-suite headers
            INCLUDES += $(SEARCH_crypto-suite-psc3)/include
            INCLUDES += $(SEARCH_crypto-suite-psc3)/include/api

            # - CS.lib: core API symbols (Cs_Open/Cs_Cfg/Cs_Ctrl/...)
            # - CS-Secure.lib: secure peripheral base address bindings (CS_MXAES_BASE/...)
            # Library variant must match the toolchain enum/char ABI and the selected 
            # floating-point ABI.
            ifeq ($(VFP_SELECT), hardfp)
                CS_FLOAT_ABI := hard
            else ifeq ($(VFP_SELECT), softfp)
                CS_FLOAT_ABI := softfp
            endif

            ifeq ($(TOOLCHAIN), GCC_ARM)
                # GCC with MTB: -fshort-enums (variable-size enums), 4-byte wchar_t
                LDLIBS += $(SEARCH_crypto-suite-psc3)/lib/shortenum-noshortchar-$(CS_FLOAT_ABI)/CS.lib
                LDLIBS += $(SEARCH_crypto-suite-psc3)/lib/shortenum-noshortchar-$(CS_FLOAT_ABI)/CS-Secure.lib
            else ifeq ($(TOOLCHAIN), ARM)
                # ARM Compiler with MTB: -fshort-enums, 2-byte wchar_t.
                LDLIBS += $(SEARCH_crypto-suite-psc3)/lib/shortenum-shortchar-$(CS_FLOAT_ABI)/CS.lib
                LDLIBS += $(SEARCH_crypto-suite-psc3)/lib/shortenum-shortchar-$(CS_FLOAT_ABI)/CS-Secure.lib
            else ifeq ($(TOOLCHAIN), IAR)
                # IAR: short enums, standard wchar_t
                LDLIBS += $(SEARCH_crypto-suite-psc3)/lib/shortenum-noshortchar-$(CS_FLOAT_ABI)/CS.lib
                LDLIBS += $(SEARCH_crypto-suite-psc3)/lib/shortenum-noshortchar-$(CS_FLOAT_ABI)/CS-Secure.lib
            endif
        endif
    endif
endif

################################################################################
# Platform-specific XMSS key conversion handler for PSC3_P8
################################################################################
# NOTE: Key generation now happens via Make restart pattern (target above)
define PLATFORM_CONVERT_XMSS_KEY
    # XMSS keys are not compatible with SFLASH storage
    # Key has already been generated by target above, no additional processing needed
    $$(info [Bootloader] XMSS key generated at: $$(AUTOGENERATED_DIR)/xmss_sign_key.c)
endef

################################################################################
# Platform-specific LMS key conversion handler for PSC3_P8
################################################################################
# NOTE: Key generation now happens via Make restart pattern (target above)
define PLATFORM_CONVERT_LMS_KEY
    # LMS keys are not compatible with SFLASH storage
    # Key has already been generated by target above, no additional processing needed
    $$(info [Bootloader] LMS key generated at: $$(AUTOGENERATED_DIR)/lms_sign_key.c)
endef

################################################################################
# Platform-specific ML-DSA key conversion handler for PSC3_P8
################################################################################
define PLATFORM_CONVERT_MLDSA_KEY
    # ML-DSA keys are not compatible with SFLASH storage
    # Key has already been generated by target above, no additional processing needed
    $$(info [Bootloader] ML-DSA key generated at: $$(AUTOGENERATED_DIR)/ml_dsa_sign_key.c)
endef

################################################################################
# Platform-specific ECDSA key conversion handler for PSC3_P8
################################################################################
# PSC3_P8 uses pre-provisioned keys from manufacturing, so key conversion
# is only needed when NOT using SFLASH_KEYS
# NOTE: Key generation now happens via Make restart pattern (target above)
define PLATFORM_CONVERT_ECDSA_KEY
    # Key has already been generated by target above, no additional processing needed
    $$(info [Bootloader] ECDSA key generated at: $$(AUTOGENERATED_DIR)/ecdsa_sign_key.c)
endef

################################################################################
# Platform-specific ECDSA public key preparation for SFLASH provisioning - PSC3_P8
################################################################################
# PSC3_P8 devices are pre-provisioned with OEM develop public key in SFLASH
define PLATFORM_PREPARE_ECDSA_SFLASH_KEY
    $$(info [Bootloader] ECDSA validation will use OEM develop public key stored in sflash, make sure you use valid private key to sign your images)
endef

################################################################################
# Platform-specific EC256 encryption key conversion handler for PSC3_P8
################################################################################
# NOTE: Key generation happens via Make restart pattern (target above)
define PLATFORM_CONVERT_EC256_ENC_KEY
    # Key has already been generated by target above, no additional processing needed
    $$(info [Bootloader] EC256 key generated at: $$(AUTOGENERATED_DIR)/enc_key.c)
endef
