################################################################################
# \file app.mk
# \version 4.0
#
# \brief
# Configuration file for adding/removing source files. Modify this file
# to suit the application needs.
#
################################################################################
# \copyright
# (c) 2019-2026, Infineon Technologies AG, or an affiliate of Infineon
# Technologies AG.  All rights reserved.
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
################################################################################

################################################################################
# Paths
################################################################################
# Define platform config path
PLATFORM_PATH = ../platforms/$(PLATFORM)
# Define build artifacts output path
BINARY_OUT_PATH = build/$(TARGET)/$(CONFIG)
# Promote this project's program (.hex) to the application-level project_hex/
# directory so it can be combined/signed with the other subprojects.
MTB_APPLICATION_PROMOTE=true
# Define edgeprotecttools path
EDGE_PROTECT_TOOLS := edgeprotecttools
# Path to default project security assets
SECURITY_ASSETS_DIR = $(PLATFORM_PATH)/security_assets
# Autogenerated files path
AUTOGENERATED_DIR = $(PLATFORM_PATH)/generated
# Set Python path
ifeq ($(CY_PYTHON_PATH),)
    ifeq ($(OS),Windows_NT)
        CY_PYTHON_PATH?=$(shell which python)
    else
        CY_PYTHON_PATH?=$(shell which python3)
    endif
endif # checking for Python path
################################################################################
# Make includes
################################################################################
# Include feature_config.mk early (before platform.mk) so platform.mk can use its variables
# for key generation logic. Use -include because the file might not exist on first build.
-include $(AUTOGENERATED_DIR)/feature_config.mk

-include $(PLATFORM_PATH)/platform.mk

# Define mcuboot core path
ifeq ($(SEARCH_mcuboot), )
    SEARCH_mcuboot = $(PLATFORM_MCUBOOT_SEARCH)
endif
MCUBOOT_PATH = $(SEARCH_mcuboot)
# Define mcuboot cypress path
MCUBOOT_CY_PATH = $(MCUBOOT_PATH)/boot/cypress

# Include memorymap.mk after platform.mk so LDFLAGS can use its variables
-include $(AUTOGENERATED_DIR)/memorymap.mk

################################################################################
# Mbedtls paths
################################################################################
ENABLE_PSA_CRYPTOLITE ?= 1
MBEDTLS_CONFIG_FILE="\"../platforms/$(PLATFORM)/mcuboot_config/ifx_mbedtls_crypto_config.h\""
MBEDTLS_USER_CONFIG_FILE="\"../platforms/$(PLATFORM)/mcuboot_config/ifx_mbedtls_target_config.h\""
MBEDTLS_PSA_CRYPTO_CONFIG_FILE ?="\"../platforms/$(PLATFORM)/mcuboot_config/ifx_psa_crypto_config.h\""

################################################################################
# Variables
################################################################################
# Switch on a bootstrap support in swap mode (0 - off, 1 - on)
USE_BOOTSTRAP ?= 1
USE_PSVP_NO_BOOTROM ?= 0
################################################################################
# Linker defs
################################################################################

ifeq ($(TOOLCHAIN), GCC_ARM)
    LINKER_SUFIX = ld
else ifeq ($(TOOLCHAIN), IAR)
    LINKER_SUFIX = icf
else ifeq ($(TOOLCHAIN), ARM)
    LINKER_SUFIX = sct
endif

$(info )
$(info ==============================================================================)
$(info = Build Configuration =)
$(info ==============================================================================)

# Track Make restarts with custom variable for debugging (helps identify two-pass build behavior)
_BOOTLOADER_RESTART_COUNT := $(if $(MAKE_RESTARTS),$(MAKE_RESTARTS),0)
ifeq ($(_BOOTLOADER_RESTART_COUNT), 0)
    $(info [Bootloader] Restart count 0 : Initial parse )
else ifeq ($(_BOOTLOADER_RESTART_COUNT), 1)
    $(info [Bootloader] Restart count 1 : feature_config.mk was generated or changed)
else ifeq ($(_BOOTLOADER_RESTART_COUNT), 2)
    $(info [Bootloader] Restart count 2 : sign_key.c (and enc_key.c) was generated)
else
    $(error [Bootloader] Restart count $(_BOOTLOADER_RESTART_COUNT) : Unexpected multiple restarts)
endif

$(info [Bootloader] Family: $(FAMILY), Platform: $(PLATFORM))
$(info [Bootloader] Tools Directory: $(CY_TOOLS_DIR))
$(info [Bootloader] Platform path: $(PLATFORM_PATH))
$(info [Bootloader] Dependencies path: $(CY_GETLIBS_DEPS_PATH))
$(info [Bootloader] Memory map: $(MEMORY_MAP))

# Only set linker memory definitions if memorymap.mk has been loaded
# This ensures we use the correct memory layout, not the default values
ifneq ($(wildcard $(AUTOGENERATED_DIR)/memorymap.mk),)
FLASH_ORIGIN ?= $(BOOTLOADER_ORIGIN)
FLASH_SIZE ?= $(BOOTLOADER_SIZE)

$(info [Bootloader] RAM: origin=0x$(shell printf '%x' $(BOOTLOADER_RAM_ORIGIN)) size=0x$(shell printf '%x' $(BOOTLOADER_RAM_SIZE)))
$(info [Bootloader] FLASH: origin=0x$(shell printf '%x' $(FLASH_ORIGIN)) size=0x$(shell printf '%x' $(FLASH_SIZE)) offset=0x$(shell printf '%x' $(FLASH_OFS)))
ifeq ($(TOOLCHAIN), GCC_ARM)
    LDFLAGS += -Wl,--defsym=RAM_ORIGIN=$(BOOTLOADER_RAM_ORIGIN)
    LDFLAGS += -Wl,--defsym=RAM_SIZE=$(BOOTLOADER_RAM_SIZE)
    LDFLAGS += -Wl,--defsym=FLASH_ORIGIN=$(FLASH_ORIGIN)
    LDFLAGS += -Wl,--defsym=FLASH_SIZE=$(FLASH_SIZE)
    LDFLAGS += -Wl,--defsym=FLASH_OFS=$(FLASH_OFS)
    LDFLAGS += -Wl,--no-warn-rwx-segments

else ifeq ($(TOOLCHAIN), IAR)
    LDFLAGS += --config_def RAM_ORIGIN=$(BOOTLOADER_RAM_ORIGIN)
    LDFLAGS += --config_def RAM_SIZE=$(BOOTLOADER_RAM_SIZE)
    LDFLAGS += --config_def FLASH_ORIGIN=$(FLASH_ORIGIN)
    LDFLAGS += --config_def FLASH_SIZE=$(FLASH_SIZE)
    LDFLAGS += --config_def FLASH_OFS=$(FLASH_OFS)

else ifeq ($(TOOLCHAIN), ARM)
    LDFLAGS += --predefine="-DRAM_ORIGIN=$(BOOTLOADER_RAM_ORIGIN)"
    LDFLAGS += --predefine="-DRAM_SIZE=$(BOOTLOADER_RAM_SIZE)"
    LDFLAGS += --predefine="-DFLASH_ORIGIN=$(FLASH_ORIGIN)"
    LDFLAGS += --predefine="-DFLASH_SIZE=$(FLASH_SIZE)"
    LDFLAGS += --predefine="-DFLASH_OFS=$(FLASH_OFS)"
else
    $(error [Bootloader] $(TOOLCHAIN) not supported at this moment)
endif
endif  # End of memorymap.mk existence check

ifeq ($(TOOLCHAIN), IAR)
    LDFLAGS += --redirect _Printf=_PrintfTiny
endif

# Define linker path
LINKER_SCRIPT = $(PLATFORM_PATH)/$(PLATFORM_LINKER_SCRIPT).$(LINKER_SUFIX)

################################################################################
# Prebuild section
################################################################################
# Create autogenerated folder
AUTOGENERATED_DIR_RES := $(shell mkdir -p $(AUTOGENERATED_DIR))

# Check if feature_config.mk exists
FEATURE_CONFIG_EXISTS := $(wildcard $(AUTOGENERATED_DIR)/feature_config.mk)

define _BOOTLOADER_GENERATE_FEATURE_CONFIG
$(PLATFORM_PREBUILD); \
if ! cmp -s "$(AUTOGENERATED_DIR)/feature_config.mk.tmp" "$(AUTOGENERATED_DIR)/feature_config.mk"; then \
	mv -f "$(AUTOGENERATED_DIR)/feature_config.mk.tmp" "$(AUTOGENERATED_DIR)/feature_config.mk"; \
	echo "[Bootloader] feature_config.mk changed - removing generated key files to force regeneration"; \
	rm -f "$(AUTOGENERATED_DIR)/sign_key.c" "$(AUTOGENERATED_DIR)/sign_key.der" "$(AUTOGENERATED_DIR)/.sign_key.mk" "$(AUTOGENERATED_DIR)/enc_key.c" "$(AUTOGENERATED_DIR)/enc_key.der"; \
	rm -f "$(AUTOGENERATED_DIR)/ml_dsa_sign_key.c" "$(AUTOGENERATED_DIR)/.ml_dsa_sign_key.mk"; \
	rm -f "$(AUTOGENERATED_DIR)/lms_sign_key.c" "$(AUTOGENERATED_DIR)/.lms_sign_key.mk"; \
	rm -f "$(AUTOGENERATED_DIR)/xmss_sign_key.c" "$(AUTOGENERATED_DIR)/.xmss_sign_key.mk"; \
	rm -f "$(AUTOGENERATED_DIR)/ecdsa_sign_key.c" "$(AUTOGENERATED_DIR)/.ecdsa_sign_key.mk"; \
	rm -f "$(AUTOGENERATED_DIR)/ec256_enc_key.c" "$(AUTOGENERATED_DIR)/.ec256_enc_key.mk"; \
else \
	rm -f "$(AUTOGENERATED_DIR)/feature_config.mk.tmp"; \
fi
endef

define _BOOTLOADER_GENERATE_MEMORYMAP
$(CY_PYTHON_PATH) $(MCUBOOT_CY_PATH)/scripts/memorymap_rework.py run -p ../platforms/$(PLATFORM)/memory_maps/platform.json -i $(MEMORY_MAP) -o $(AUTOGENERATED_DIR)/ -n memorymap > $(AUTOGENERATED_DIR)/memorymap.mk.tmp; \
if ! cmp -s "$(AUTOGENERATED_DIR)/memorymap.mk.tmp" "$(AUTOGENERATED_DIR)/memorymap.mk"; then \
	mv -f "$(AUTOGENERATED_DIR)/memorymap.mk.tmp" "$(AUTOGENERATED_DIR)/memorymap.mk"; \
else \
	rm -f "$(AUTOGENERATED_DIR)/memorymap.mk.tmp"; \
fi
endef

PREBUILD = $(_BOOTLOADER_GENERATE_FEATURE_CONFIG); $(_BOOTLOADER_GENERATE_MEMORYMAP)

.PHONY: FORCE
ifneq ($(filter build_proj build,$(MAKECMDGOALS)),)
$(AUTOGENERATED_DIR)/feature_config.mk: FORCE
	$(_BOOTLOADER_GENERATE_FEATURE_CONFIG)
$(AUTOGENERATED_DIR)/memorymap.mk: FORCE
	$(_BOOTLOADER_GENERATE_MEMORYMAP)
endif

################################################################################
# Defines
################################################################################
DEFINES += RAM_ORIGIN=$(BOOTLOADER_RAM_ORIGIN)
DEFINES += RAM_SIZE=$(BOOTLOADER_RAM_SIZE)
DEFINES += $(PLATFORM_DEFINES)
DEFINES += $(PLATFORM)
DEFINES += $(FAMILY)
DEFINES += CY_RETARGET_IO_NO_FLOAT
DEFINES += MCUBOOT_LOG_LEVEL=$(MCUBOOT_LOG_LEVEL)
DEFINES += MCUBOOT_IMAGE_NUMBER=$(MCUBOOT_IMAGE_NUMBER)
DEFINES += MEMORY_ALIGN=$(PLATFORM_MEMORY_ALIGN)
DEFINES += PLATFORM_MAX_TRAILER_PAGE_SIZE=$(PLATFORM_MAX_TRAILER_PAGE_SIZE)
DEFINES += MCUBOOT_MAX_IMG_SECTORS=$(MAX_IMG_SECTORS)
DEFINES += MBEDTLS_CONFIG_FILE=$(MBEDTLS_CONFIG_FILE)
DEFINES += MBEDTLS_USER_CONFIG_FILE=$(MBEDTLS_USER_CONFIG_FILE)
DEFINES += MBEDTLS_PSA_CRYPTO_CONFIG_FILE=$(MBEDTLS_PSA_CRYPTO_CONFIG_FILE)

# Only run validation and key operations if feature_config.mk exists
# Rationale: feature_config.mk contains critical configuration variables (like MCUBOOT_SKIP_BOOT_VALIDATION,
# MCUBOOT_SKIP_UPGRADE_VALIDATION, ENC_IMG, etc.) that are needed for proper validation logic.
# If the file doesn't exist yet:
# - On first build: file will be created by the target, Make will restart, then validation runs
# - Variables from feature_config.mk would be undefined, causing incorrect configuration
# By checking FEATURE_CONFIG_EXISTS, we ensure validation only runs after Make has loaded the config file.
# Additional benefit: Most $(error ...) calls are inside this block, which means they won't prevent
# 'make clean_proj' from running if feature_config.mk doesn't exist. This allows cleanup even when
# the build configuration has errors. Note: Some errors outside this block (e.g., unsupported toolchain
# at line 111) can still prevent cleanup, but those are fundamental issues that must be fixed first.
ifneq ($(FEATURE_CONFIG_EXISTS),)

IMAGE_VALIDATION_ENABLED = 0
ifeq ($(ENABLE_PSA_CRYPTOLITE),1)
    DEFINES += ENABLE_PSA_CRYPTOLITE=$(ENABLE_PSA_CRYPTOLITE)
endif

ifeq ($(USE_HW_KEY), 1)
    DEFINES += MCUBOOT_HW_KEY
endif

ifeq ($(USE_SHARED_SLOT), 1)
    DEFINES += USE_SHARED_SLOT=$(USE_SHARED_SLOT)
else
    DEFINES += USE_SHARED_SLOT=0 
endif

ifneq ($(MCUBOOT_SKIP_BOOT_VALIDATION), 1)
    # Enable image validation as we do not skip boot validation
    IMAGE_VALIDATION_ENABLED = 1
    DEFINES += MCUBOOT_VALIDATE_PRIMARY_SLOT
endif

ifeq ($(MCUBOOT_SKIP_UPGRADE_VALIDATION), 1)
    DEFINES += MCUBOOT_SKIP_VALIDATE_SECONDARY_SLOT
else
    # Enable image validation as we do not skip upgrade validation
    IMAGE_VALIDATION_ENABLED = 1
endif

ifeq ($(USE_CRYPTO_HW), 1)
    DEFINES += CY_CRYPTO_HAL_DISABLE
    DEFINES += CY_MBEDTLS_HW_ACCELERATION
endif

ifeq ($(USE_WDT), 1)
    DEFINES += USE_WDT
endif

ifeq ($(USE_OVERWRITE), 1)
    DEFINES += MCUBOOT_OVERWRITE_ONLY
    ifeq ($(USE_SW_DOWNGRADE_PREV), 1)
        DEFINES += MCUBOOT_DOWNGRADE_PREVENTION
    endif
else
    ifeq ($(USE_BOOTSTRAP), 1)
        DEFINES += MCUBOOT_BOOTSTRAP
    endif
    ifeq ($(USE_SW_DOWNGRADE_PREV), 1)
        $(error [Bootloader] SW_DOWNGRADE_PREV doesn't work with SWAP)
    endif
endif

ifeq ($(USE_EXTERNAL_FLASH), 1)
    DEFINES += CY_BOOT_USE_EXTERNAL_FLASH
endif

ifeq ($(USE_XIP), 1)
    DEFINES += USE_XIP

    ifneq ($(USE_EXTERNAL_FLASH), 1)
        $(error [Bootloader] USE_EXTERNAL_FLASH must be specified for XIP mode)
    endif
endif

ifneq ($(MCUBOOT_IMAGE_NUMBER), 1)
    ifeq ($(MCUBOOT_DEPENDENCY_CHECK), 1)
        DEFINES += MCUBOOT_DEPENDENCY_CHECK
    endif
endif

ifeq ($(USE_MEASURED_BOOT), 1)
    DEFINES += MCUBOOT_MEASURED_BOOT
    DEFINES += MCUBOOT_DATA_SHARING
    DEFINES += MAX_BOOT_RECORD_SZ=$(BOOT_SHARED_DATA_RECORD_SIZE)
    DEFINES += MCUBOOT_SHARED_DATA_BASE=$(BOOT_SHARED_DATA_ADDRESS)
    DEFINES += MCUBOOT_SHARED_DATA_SIZE=$(BOOT_SHARED_DATA_SIZE)
    DEFINES += SW_MODULE_START_ID=1
endif

ifeq ($(USE_MCUBOOT_MULTI_MEMORY_LOAD), 1)
    DEFINES += MCUBOOT_MULTI_MEMORY_LOAD
    DEFINES += MCUBOOT_RAM_LOAD
    DEFINES += MULTIPLE_EXECUTABLE_RAM_REGIONS
else ifeq ($(USE_MCUBOOT_RAM_LOAD), 1)
    DEFINES += MCUBOOT_RAM_LOAD=1
    DEFINES += IMAGE_EXECUTABLE_RAM_START=$(IMAGE_EXECUTABLE_RAM_START)
    DEFINES += IMAGE_EXECUTABLE_RAM_SIZE=$(IMAGE_EXECUTABLE_RAM_SIZE)
endif

ifeq ($(USE_STAGE_RAM_APPS), 1)
    DEFINES += STAGE_RAM_APPS=1
    DEFINES += RAM_APP_STAGING_EXT_MEM_ADDR=$(RAM_APP_STAGING_EXT_MEM_ADDR)
    DEFINES += RAM_APP_STAGING_SRAM_MEM_ADDR=$(RAM_APP_STAGING_SRAM_MEM_ADDR)
    DEFINES += RAM_APP_STAGING_SIZE=$(RAM_APP_STAGING_SIZE)

    ifeq ($(RAM_APP_RESET_TRIGGER), 1)
        DEFINES += RAM_APP_RESET_TRIGGER=1
    endif
endif

FIH_PROFILE_LEVEL_LIST = OFF LOW MEDIUM HIGH
ifneq ($(filter $(FIH_PROFILE_LEVEL), $(FIH_PROFILE_LEVEL_LIST)),)
    ifneq ($(FIH_PROFILE_LEVEL), OFF)
        DEFINES += MCUBOOT_FIH_PROFILE_ON
        DEFINES += MCUBOOT_FIH_PROFILE_$(FIH_PROFILE_LEVEL)
    endif
endif

ifeq ($(ENC_IMG), 1)
    # Check if image validation is enabled
    ifneq ($(IMAGE_VALIDATION_ENABLED), 1)
        $(error [Bootloader] Image encryption requires image validation to be enabled)
    endif

    DEFINES += ENC_IMG=1
    ifeq ($(USE_XIP), 1)
        $(error [Bootloader] MCUBOOT_ENC_IMAGES_XIP is not implemented yet)
    endif
endif

ifeq ($(USE_HW_ROLLBACK_PROT), 1)
    DEFINES += MCUBOOT_HW_ROLLBACK_PROT
endif

################################################################################
# Key Detection Logic
################################################################################
ifeq ($(IMAGE_VALIDATION_ENABLED), 1)

    $(info [Bootloader] Image validation: ENABLED)
    VERSION_PYTHON := $(shell python --version)
    $(info [Bootloader] Python version: $(VERSION_PYTHON))
    WHERE_PYTHON := $(shell where python)
    $(info [Bootloader] Python path: $(WHERE_PYTHON))
    VERSION_EPT := $(shell edgeprotecttools version)
    $(info [Bootloader] Edgeprotecttools version: $(VERSION_EPT))
    WHERE_EPT := $(shell where edgeprotecttools)
    $(info [Bootloader] Edgeprotecttools path: $(WHERE_EPT))

    # Handle LMS (Lamport-Merkle Signature) public key configuration
    ifneq ($(LMS_PUBLIC_KEY), )
        $(info [Bootloader] LMS public key: $(LMS_PUBLIC_KEY))
        
        # Validate that the key file exists
        ifeq ($(wildcard $(LMS_PUBLIC_KEY)),)
            $(error [Bootloader] LMS public key file not found: $(LMS_PUBLIC_KEY))
        endif
                
        DEFINES += USE_LMS
        $(info [Bootloader] Hash: SHA256)
        DEFINES += USE_SHA256
        
        # Platform-specific key conversion logic (defined in platform.mk)
        $(eval $(PLATFORM_CONVERT_LMS_KEY))

        SIGNING_PUBLIC_KEY = 1
    endif

    # Handle XMSS (eXtended Merkle Signature Scheme) public key configuration
    ifneq ($(XMSS_PUBLIC_KEY), )
        $(info [Bootloader] XMSS public key: $(XMSS_PUBLIC_KEY))
        
        # Validate that the key file exists
        ifeq ($(wildcard $(XMSS_PUBLIC_KEY)),)
            $(error [Bootloader] XMSS public key file not found: $(XMSS_PUBLIC_KEY))
        endif
                
        DEFINES += MCUBOOT_SIGN_XMSS=1
        DEFINES += USE_SHA256
        
        # Platform-specific key conversion logic (defined in platform.mk)
        $(eval $(PLATFORM_CONVERT_XMSS_KEY))
        
        SIGNING_PUBLIC_KEY = 1
    endif

    # Handle ML-DSA (Module Lattice Digital Signature Algorithm) public key configuration
    ifneq ($(MLDSA_PUBLIC_KEY), )
        $(info [Bootloader] ML-DSA public key: $(MLDSA_PUBLIC_KEY))

        # Validate that the key file exists
        ifeq ($(wildcard $(MLDSA_PUBLIC_KEY)),)
            $(error [Bootloader] ML-DSA public key file not found: $(MLDSA_PUBLIC_KEY))
        endif

        # Platform-specific key conversion logic (defined in platform.mk)
        $(eval $(PLATFORM_CONVERT_MLDSA_KEY))

        # Configure ML-DSA variant based on public key algorithm
        $(info [Bootloader] ML-DSA public key algorithm: $(MLDSA_PUBLIC_KEY_ALG))
        ifeq ($(MLDSA_PUBLIC_KEY_ALG), 44)
            $(info [Bootloader] Using ML-DSA-44)
            DEFINES += USE_MLDSA44
        else ifeq ($(MLDSA_PUBLIC_KEY_ALG), 65)
            $(info [Bootloader] Using ML-DSA-65)
            DEFINES += USE_MLDSA65
        else ifeq ($(MLDSA_PUBLIC_KEY_ALG), 87)
            $(info [Bootloader] Using ML-DSA-87)
            DEFINES += USE_MLDSA87
        else
            # Invalid ML-DSA algorithm - ML-DSA only defines three algorithms: 44, 65, and 87
            $(error [Bootloader] Invalid ML-DSA public key algorithm '$(MLDSA_PUBLIC_KEY_ALG)'. ML-DSA defines exactly three algorithms: 44, 65, and 87)
        endif

        # Configure hash algorithm based on MLDSA_SIG_HASH setting
        ifeq ($(MLDSA_SIG_HASH), 256)
            $(info [Bootloader] ML-DSA Hash: SHA256)
            DEFINES += USE_SHA256
        else ifeq ($(MLDSA_SIG_HASH), 384)
            $(info [Bootloader] ML-DSA Hash: SHA384)
            DEFINES += USE_SHA384
        else ifeq ($(MLDSA_SIG_HASH), 512)
            $(info [Bootloader] ML-DSA Hash: SHA512)
            DEFINES += USE_SHA512
        else
            # Default hash based on ML-DSA variant when MLDSA_SIG_HASH is not set
            ifeq ($(MLDSA_PUBLIC_KEY_ALG), 44)
                $(info [Bootloader] ML-DSA Hash: SHA256 (default for ML-DSA-44))
                DEFINES += USE_SHA256
            else ifeq ($(MLDSA_PUBLIC_KEY_ALG), 65)
                $(info [Bootloader] ML-DSA Hash: SHA384 (default for ML-DSA-65))
                DEFINES += USE_SHA384
            else ifeq ($(MLDSA_PUBLIC_KEY_ALG), 87)
                $(info [Bootloader] ML-DSA Hash: SHA512 (default for ML-DSA-87))
                DEFINES += USE_SHA512
            endif
        endif

        SIGNING_PUBLIC_KEY = 1
    endif

    # Handle ECDSA (Elliptic Curve Digital Signature Algorithm) public key configuration
    ifneq ($(ECDSA_PUBLIC_KEY), )
        $(info [Bootloader] ECDSA public key: $(ECDSA_PUBLIC_KEY))

        # Validate that the key file exists
        ifeq ($(wildcard $(ECDSA_PUBLIC_KEY)),)
            $(error [Bootloader] ECDSA public key file not found: $(ECDSA_PUBLIC_KEY))
        endif

        # Platform-specific key conversion logic (defined in platform.mk)
        $(eval $(PLATFORM_CONVERT_ECDSA_KEY))

        # Configure hash algorithm based on public key sizes
        $(info [Bootloader] ECDSA public key size: $(ECDSA_PUBLIC_KEY_SIZE))
        ifeq ($(ECDSA_PUBLIC_KEY_SIZE), 256)
            $(info [Bootloader] Hash: SHA256)
            DEFINES += USE_SHA256
        else ifeq ($(ECDSA_PUBLIC_KEY_SIZE), 384)
            $(info [Bootloader] Hash: SHA384)
            DEFINES += USE_SHA384
        else ifeq ($(ECDSA_PUBLIC_KEY_SIZE), 521)
            $(info [Bootloader] Hash: SHA512)
            DEFINES += USE_SHA512
        else
            # Unsupported key size - only P-256, P-384, and P-521 are supported
            $(error [Bootloader] Unsupported ECDSA public key size: $(ECDSA_PUBLIC_KEY_SIZE))
        endif
        SIGNING_PUBLIC_KEY = 1
    endif

    ifeq ($(SIGNING_PUBLIC_KEY), )
        $(error [Bootloader] Image validation is enabled but no signing public key is specified, check validation_key settings.)
    endif

    # Handle image encryption configuration
    ifeq ($(ENC_IMG), 1)
        # Determine encryption method and handle key generation accordingly
        ifeq ($(USE_ENCRYPTION_KDF_CTR), 1)
            $(info [Bootloader] Encryption: encryption with CS-PSC3X8 KDF-CMAC is set)
            DEFINES += USE_ENCRYPTION_KDF_CTR=$(USE_ENCRYPTION_KDF_CTR)
        else
            $(info [Bootloader] Encryption: encryption with Eliptic Curve (EC256) key is set)
            # Handle EC256 encryption private key configuration
            ifneq ($(ENC_PRIVATE_KEY), )
                $(info [Bootloader] Encryption private key: $(ENC_PRIVATE_KEY))

                # Platform-specific key conversion logic (defined in platform.mk)
                $(eval $(PLATFORM_CONVERT_EC256_ENC_KEY))
            else
                $(error [Bootloader] ENC_PRIVATE_KEY must be set in feature_config.json encryption_key field when ENC_IMG=1)
            endif
        endif
    endif

    # Handle SFlash key storage configuration
    ifeq ($(USE_SFLASH_KEYS), 1)
        $(info [Bootloader] Sflash keys: using SFlash key storage with pre-provisioned keys)
        DEFINES += SFLASH_KEYS

        # Clean up C array key files (not needed with SFLASH keys)
        REMOVE_C_KEYS := $(shell rm -f $(AUTOGENERATED_DIR)/enc_key.c $(AUTOGENERATED_DIR)/sign_key.c $(AUTOGENERATED_DIR)/ecdsa_sign_key.c $(AUTOGENERATED_DIR)/.ecdsa_sign_key.mk)
        # Validate key compatibility
        ifneq ($(LMS_PUBLIC_KEY), )
            $(error [Bootloader] LMS signature keys are not compatible with SFlash key storage.)
        endif

        ifneq ($(XMSS_PUBLIC_KEY), )
            $(error [Bootloader] XMSS signature keys are not compatible with SFlash key storage.)
        endif

        ifneq ($(MLDSA_PUBLIC_KEY), )
            $(error [Bootloader] ML-DSA signature keys are not compatible with SFlash key storage.)
        endif

        # Platform-specific ECDSA public key preparation for SFLASH provisioning (defined in platform.mk)
        $(eval $(PLATFORM_PREPARE_ECDSA_SFLASH_KEY))
    endif
else
    # Clean up any existing generated key files to avoid conflicts with disabled validation
    REMOVE_C_KEYS := $(shell rm -f $(AUTOGENERATED_DIR)/sign_key.c $(AUTOGENERATED_DIR)/sign_key.der $(AUTOGENERATED_DIR)/.sign_key.mk $(AUTOGENERATED_DIR)/enc_key.c $(AUTOGENERATED_DIR)/enc_key.der \
        $(AUTOGENERATED_DIR)/ml_dsa_sign_key.c $(AUTOGENERATED_DIR)/.ml_dsa_sign_key.mk \
        $(AUTOGENERATED_DIR)/lms_sign_key.c $(AUTOGENERATED_DIR)/.lms_sign_key.mk \
        $(AUTOGENERATED_DIR)/xmss_sign_key.c $(AUTOGENERATED_DIR)/.xmss_sign_key.mk \
        $(AUTOGENERATED_DIR)/ecdsa_sign_key.c $(AUTOGENERATED_DIR)/.ecdsa_sign_key.mk \
        $(AUTOGENERATED_DIR)/ec256_enc_key.c $(AUTOGENERATED_DIR)/.ec256_enc_key.mk)

    $(info [Bootloader] Image validation: DISABLED)
    $(info [Bootloader] Hash: used default SHA256)
    DEFINES += USE_SHA256
endif
endif

################################################################################
# Sources
################################################################################
$(info [Bootloader] Files in AUTOGENERATED_DIR: $(wildcard $(AUTOGENERATED_DIR)/*))
SOURCES += $(PLATFORM_SOURCES)
SOURCES += \
    $(MCUBOOT_PATH)/boot/bootutil/src/boot_record.c\
    $(MCUBOOT_PATH)/boot/bootutil/src/bootutil_misc.c\
    $(MCUBOOT_PATH)/boot/bootutil/src/bootutil_public.c\
    $(MCUBOOT_PATH)/boot/bootutil/src/crc32c.c\
    $(MCUBOOT_PATH)/boot/bootutil/src/fault_injection_hardening.c\
    $(MCUBOOT_PATH)/boot/bootutil/src/fault_injection_hardening_delay_rng_mbedtls.c\
    $(MCUBOOT_PATH)/boot/bootutil/src/loader.c\
    $(MCUBOOT_PATH)/boot/bootutil/src/swap_misc.c\
    $(MCUBOOT_PATH)/boot/bootutil/src/swap_scratch.c\
    $(MCUBOOT_PATH)/boot/bootutil/src/swap_status_misc.c\
    $(MCUBOOT_PATH)/boot/bootutil/src/swap_status_part.c\
    $(MCUBOOT_PATH)/boot/bootutil/src/swap_status.c\
    $(MCUBOOT_PATH)/boot/bootutil/src/tlv.c\
    $(MCUBOOT_CY_PATH)/platforms/memory/cy_flash_map.c\
    $(wildcard $(AUTOGENERATED_DIR)/*.c)\
    $(wildcard $(PLATFORM_PATH)/*.c)\
    $(wildcard $(MCUBOOT_CY_PATH)/platforms/memory/$(FAMILY)/*.c)

# Exclude encrypted.c when using CS-PSC3X8 crypto (PSC3_P8 and PSC3_M6 platforms)
ifeq ($(filter $(FAMILY),PSC3_P8 PSC3_M6),$(FAMILY))
    ifeq ($(USE_ENCRYPTION_KDF_CTR), 1)
        SOURCES += $(MCUBOOT_CY_PATH)/platforms/crypto/$(FAMILY)/cs_encrypted.c
    else
        SOURCES += $(MCUBOOT_PATH)/boot/bootutil/src/encrypted.c
    endif
else
    SOURCES += $(MCUBOOT_PATH)/boot/bootutil/src/encrypted.c
endif
    
ifeq ($(USE_EXTERNAL_FLASH), 1)
    ifeq ($(USE_SERIAL_FLASH_LIBRARY),)
        SOURCES += $(wildcard $(MCUBOOT_CY_PATH)/platforms/memory/external_memory/external_memory.c)
    endif
    SOURCES += $(wildcard $(MCUBOOT_CY_PATH)/platforms/memory/$(FAMILY)/flash_qspi/*.c)
endif

SOURCES += $(wildcard $(MCUBOOT_CY_PATH)/platforms/crypto/$(FAMILY)/*.c)

# Include XMSS crypto sources from cy-mbedtls-acceleration if XMSS public key is used
ifneq ($(XMSS_PUBLIC_KEY), )
    SOURCES += $(wildcard $(SEARCH_cy-mbedtls-acceleration)/COMPONENT_CAT1/pqc/xmss/*.c)
endif

# Include WolfSSL for ML-DSA verification if ML-DSA key is used
ifneq ($(MLDSA_PUBLIC_KEY), )
    # WolfSSL root directory - use ifx-wolfcrypto shared library
    WOLFSSL_ROOT = $(SEARCH_ifx-wolfcrypto)
    
    # Include WolfSSL headers (library root for <wolfssl/wolfcrypt/*.h>)
    INCLUDES += $(WOLFSSL_ROOT)
    # Include platform-specific WolfSSL user_settings.h
    INCLUDES += $(PLATFORM_PATH)/wolfssl
    
    # WolfSSL dilithium and SHA3 sources (minimal set for ML-DSA verification only)
    SOURCES += $(WOLFSSL_ROOT)/wolfcrypt/src/dilithium.c
    SOURCES += $(WOLFSSL_ROOT)/wolfcrypt/src/sha3.c
    
    # Enable WolfSSL user settings
    DEFINES += WOLFSSL_USER_SETTINGS
endif

ifeq ($(USE_HW_ROLLBACK_PROT), 1)
    SOURCES += $(wildcard $(MCUBOOT_CY_PATH)/platforms/security_counter/*.c)
endif

ifeq ($(FIH_PROFILE_LEVEL), HIGH)
    SOURCES += $(wildcard $(MCUBOOT_CY_PATH)/platforms/boot_rng/*.c)
endif

SOURCES += $(wildcard $(SEARCH_ifx-mbedtls)/3rdparty/p256-m/*.c)
SOURCES += $(wildcard $(SEARCH_ifx-mbedtls)/3rdparty/p256-m/p256-m/*.c)

################################################################################
# Includes
################################################################################
INCLUDES += $(PLATFORM_INCLUDES)
INCLUDES += \
    $(MCUBOOT_PATH)/boot/bootutil/include\
    $(MCUBOOT_PATH)/boot/bootutil/include/bootutil\
    $(MCUBOOT_PATH)/boot/bootutil/include/bootutil/crypto\
    $(MCUBOOT_PATH)/boot/bootutil/include/bootutil/crypto/$(FAMILY)\
    $(MCUBOOT_PATH)/bootutil/include/bootutil\
    $(MCUBOOT_PATH)/boot/bootutil/src\
    $(MCUBOOT_CY_PATH)/libs/watchdog\
    $(MCUBOOT_CY_PATH)/platforms/memory\
    $(MCUBOOT_CY_PATH)/platforms/memory/sysflash\
    $(MCUBOOT_CY_PATH)/platforms/memory/flash_map_backend\
    $(MCUBOOT_CY_PATH)/platforms/memory/$(FAMILY)\
    $(MCUBOOT_CY_PATH)/platforms/memory\
    $(PLATFORM_PATH)/mcuboot_config\
    $(PLATFORM_PATH)\
    $(AUTOGENERATED_DIR)

ifeq ($(USE_EXTERNAL_FLASH), 1)
    INCLUDES += $(MCUBOOT_CY_PATH)/platforms/memory/$(FAMILY)/flash_qspi
    INCLUDES += $(MCUBOOT_CY_PATH)/platforms/memory/external_memory
endif

INCLUDES += $(MCUBOOT_CY_PATH)/platforms/crypto/$(FAMILY)

# Include XMSS crypto path from cy-mbedtls-acceleration if XMSS public key is used
ifneq ($(XMSS_PUBLIC_KEY), )
    INCLUDES += $(SEARCH_cy-mbedtls-acceleration)/COMPONENT_CAT1/pqc/xmss
endif

ifeq ($(USE_HW_ROLLBACK_PROT), 1)
    INCLUDES += $(MCUBOOT_CY_PATH)/platforms/security_counter
endif

ifeq ($(FIH_PROFILE_LEVEL), HIGH)
    INCLUDES += $(MCUBOOT_CY_PATH)/platforms/boot_rng
endif
SOURCES += $(MCUBOOT_PATH)/boot/bootutil/src/image_validate.c

ifeq ($(ENABLE_PSA_CRYPTOLITE),1)
    INCLUDES += $(SEARCH_cy-mbedtls-acceleration)/mbedtls_PSA/mbedtls_psa_MXCryptolite
    SOURCES += $(wildcard $(SEARCH_cy-mbedtls-acceleration)/mbedtls_PSA/mbedtls_psa_MXCryptolite/*.c)
endif
################################################################################
# Flags
################################################################################
ifeq ($(TOOLCHAIN), GCC_ARM)
    CFLAGS += -Wall -Wextra
endif
CXXFLAGS += $(CFLAGS)

################################################################################
# Postbuild
################################################################################
POSTBUILD += $(PLATFORM_POSTBUILD)
POSTBUILD += $(MTB_TOOLCHAIN_GCC_ARM__BASE_DIR)/bin/arm-none-eabi-readelf -Wa $(BINARY_OUT_PATH)/$(APPNAME).elf > $(BINARY_OUT_PATH)/$(APPNAME).readelf;
POSTBUILD += $(MTB_TOOLCHAIN_GCC_ARM__BASE_DIR)/bin/arm-none-eabi-objdump -drwCS $(BINARY_OUT_PATH)/$(APPNAME).elf > $(BINARY_OUT_PATH)/$(APPNAME).lst;
################################################################################
# Add some files which will be deleted by the command 'make clean'
# You can also define a catalog to be deleted. It may be like:
#     CY_GENERATED_DIR += ./autogenerated_dir
# and it also will be removed
################################################################################
CY_GENERATED_DIR += $(AUTOGENERATED_DIR)

clean_proj_autogenerated:
	-rm -f ./memorymap.mk memorymap.c memorymap.h $(AUTOGENERATED_DIR)/feature_config.mk
	-rm -rf $(CY_GENERATED_DIR)

clean_proj: clean_proj_autogenerated
